

export const RouteKeys = {
  SPLASH: 'SPLASH',
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  APP_INTRO: 'app_intro',
  WELCOME: 'welcome',
  DESCRIBE: 'describe',

  //Need a pro tab
  MY_JOBS: 'MY_JOBS',
  REQUEST_JOBS: 'REQUEST_JOBS',
  JOB_OFFERS: 'JOB_OFFERS',
  ONGOING_JOBS: 'ONGOING_JOBS',
  COMPLETED_JOBS: 'COMPLETED_JOBS',
  //Chat Screen
  CHAT_SCREEN: 'CHAT_SCREEN',

  OTHER_USER_PROFILE: 'OTHER_USER_PROFILE',

  //Search Tab
  SEARCH: 'SEARCH',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  OFFERS_AND_TASKS: 'OFFERS_AND_TASKS',

  //SETTING TAB
  SETTINGS: 'SETTINGS',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PORTFOLIO_GALLERY: 'PORTFOLIO_GALLERY',
  PAYMENT_HISTORY: 'PAYMENT_HISTORY',
  PAYMENT_METHOD: 'PAYMENT_METHOD',
  AVAILABILITY_SCREEN: 'AVAILABILITY_SCREEN',
  HELP_AND_SUPPORT: 'HELP_AND_SUPPORT',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  DISCLAIMER: 'DISCLAIMER',


};

export const SCREEN_TITLE = {
  //Authentication Screens
  LOGIN: "Login",
  SIGNUP: "Signup",
  SIGNUP_DETAILS: 'Introduce Yourself',

  //Need a pro tab
  MY_JOBS: 'My Jobs ',
  REQUEST_JOBS: 'Request',
  JOB_OFFERS: 'Offers',
  ONGOING_JOBS: 'Ongoing',
  COMPLETED_JOBS: 'Completed',
  
  //Chat Screen
  CHAT_SCREEN: 'Chat',

  //Search Tab
  SEARCH_SCREEN: 'Search',

  //Notification Tab
  NOTIFICATION_SCREEN: 'Notifications',

  //offers and task tab
  OFFERS_AND_TASKS: 'Offers & Tasks',
  OTHER_USER_PROFILE: 'Other User Profile',

  //SETTING TAB
  SETTINGS: 'Settings',
  PROFILE_SCREEN: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  PORTFOLIO_GALLERY: 'Portfolio Gallery',
  PAYMENT_HISTORY: 'Payment History',
  PAYMENT_METHOD: 'Payment Method',
  AVAILABILITY_SCREEN: 'Availability',
  HELP_AND_SUPPORT: 'Help & Support',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  PRIVACY_POLICY: 'Privacy Policy',
  DISCLAIMER: 'Disclaimer',
};